### ISSUE TITLE
Are you sure it works under python3?

### ISSUE THREAD

**Issue by MrPumo** [botherder/snoopdroid#1]
Hi,
it seems that adb module (1.3.0) make use of % operator for bytes type object. That's not possible under python3 and raise many errors..

For example:
in snoopdroid/acquisition.py
`self.device.ConnectDevice(rsa_keys=[signer])`

generate
!!! Error: TypeError("unsupported operand type(s) for %: 'bytes' and 'bytes'",)

due to /usr/local/lib/python3.4/dist-packages/adb/adb_protocol.py
```
        msg = cls(
            command=b'CNXN', arg0=VERSION, arg1=MAX_ADB_DATA,
            data=b'host::%s\0' % banner)
```
that should be modified to
```
        msg = cls(
            command=b'CNXN', arg0=VERSION, arg1=MAX_ADB_DATA,
            data=('host::%s\0' % banner).encode())
```

and so on...

Anything I'm missing in my setup? I've followed your readme and installed dep & then pip3

Thx alot

**Comment by botherder** [comment]
It definitely works on Python3, but I am using Python 3.7. I would need to check what's the difference with earlier versions.

**Comment by MrPumo** [comment]
I think problem is here:
[https://docs.python.org/3/library/stdtypes.html#binary-sequence-types-bytes-bytearray-memoryview](https://docs.python.org/3/library/stdtypes.html#binary-sequence-types-bytes-bytearray-memoryview)
..
**printf-style Bytes Formatting**
..
`6. b'%s' is deprecated, but will not be removed during the 3.x series.`

May be py 3.4.3 raise an error while 3.7 not... I'll have a check. But adb module src may be need a review for such deprecated printf-style Bytes Formatting...

**Comment by MrPumo** [comment]
I can confirm that starting from at least python 3.6.7 it's working properly.
Thx a lot
